services:
  learnwell.coursemanagement.api:
    image: ${DOCKER_REGISTRY-}coursemanagementapi
    container_name: Learnwell.CourseManagement.API
    build:
      context: .
      dockerfile: src/LearnWell.CourseManagement.Api/Dockerfile
    depends_on:
      - coursemanagement-db
      - coursemanagement-idp
      - learnwell-redis

  coursemanagement-db:
    image: postgres:latest
    container_name: coursemanagement-db
    environment:
      POSTGRES_DB: coursemanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd1234!
      PGDATA: /var/lib/postgresql/custom_data
    volumes:
      - ./.containers/db:/var/lib/postgresql/custom_data
    ports:
      - "5433:5432"
  
  coursemanagement-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: coursemanagement-idp
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
  
  coursemanagement-seq:
    image: datalust/seq:latest
    container_name: coursemanagement.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=MySecurePassword123
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seqdata:/data
  

  learnwell-redis:
    image: redis:latest
    container_name: learnwell.redis
    restart: always
    ports:
      - "6379:6379"   

volumes:
  seqdata:
   