// <auto-generated />
using System;
using LearnWell.CourseManagement.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnWell.CourseManagement.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114001500_Additional_Migration")]
    partial class Additional_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Classes.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_classes_created_by");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.CourseClasses.CourseClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.HasKey("Id")
                        .HasName("pk_course_classes");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_course_classes_class_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_course_classes_created_by");

                    b.HasIndex("CourseId", "ClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_classes_course_id_class_id");

                    b.ToTable("course_classes", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_courses_created_by");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid?>("EnrolledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_by");

                    b.Property<bool>("FromCourseDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("from_course_default");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_enrollments_class_id");

                    b.HasIndex("EnrolledBy")
                        .HasDatabaseName("ix_enrollments_enrolled_by");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_student_id_class_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.StudentCourses.StudentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid?>("EnrolledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_by");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_courses");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_student_courses_course_id");

                    b.HasIndex("EnrolledBy")
                        .HasDatabaseName("ix_student_courses_enrolled_by");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_courses_student_id_course_id");

                    b.ToTable("student_courses", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_number");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_students_student_number");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_user_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "course:read"
                        });
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("json")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OcurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Classes.Class", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedClasses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_users_created_by");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.CourseClasses.CourseClass", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Classes.Class", "Class")
                        .WithMany("CourseClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_course_classes_classes_class_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Courses.Course", "Course")
                        .WithMany("CourseClasses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_course_classes_courses_course_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_course_classes_users_created_by");

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_courses_users_created_by");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Classes.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enrollments_classes_class_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_users_enrolled_by");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Students.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enrollments_students_student_id");

                    b.Navigation("Class");

                    b.Navigation("StaffUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.StudentCourses.StudentCourse", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Courses.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_student_courses_courses_course_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_courses_users_enrolled_by");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Students.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_student_courses_students_student_id");

                    b.Navigation("Course");

                    b.Navigation("StaffUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Students.Student", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("LearnWell.CourseManagement.Domain.Entities.Students.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_students_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.RolePermission", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_role_roles_id");

                    b.HasOne("LearnWell.CourseManagement.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Classes.Class", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("CourseClasses");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Students.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("LearnWell.CourseManagement.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("CreatedClasses");

                    b.Navigation("CreatedCourses");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
